//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace BlackTVWin10.ServiceBlack {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TVrader", Namespace="http://tempuri.org/")]
    public partial class TVrader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int ForetagsIDField;
        
        private string ForetagField;
        
        private string infoField;
        
        private int gruppField;
        
        private string GruppnamnField;
        
        private string tagField;
        
        private int VideoField;
        
        private string DatumField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ForetagsID {
            get {
                return this.ForetagsIDField;
            }
            set {
                if ((this.ForetagsIDField.Equals(value) != true)) {
                    this.ForetagsIDField = value;
                    this.RaisePropertyChanged("ForetagsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Foretag {
            get {
                return this.ForetagField;
            }
            set {
                if ((object.ReferenceEquals(this.ForetagField, value) != true)) {
                    this.ForetagField = value;
                    this.RaisePropertyChanged("Foretag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                if ((object.ReferenceEquals(this.infoField, value) != true)) {
                    this.infoField = value;
                    this.RaisePropertyChanged("info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int grupp {
            get {
                return this.gruppField;
            }
            set {
                if ((this.gruppField.Equals(value) != true)) {
                    this.gruppField = value;
                    this.RaisePropertyChanged("grupp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Gruppnamn {
            get {
                return this.GruppnamnField;
            }
            set {
                if ((object.ReferenceEquals(this.GruppnamnField, value) != true)) {
                    this.GruppnamnField = value;
                    this.RaisePropertyChanged("Gruppnamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                if ((object.ReferenceEquals(this.tagField, value) != true)) {
                    this.tagField = value;
                    this.RaisePropertyChanged("tag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Video {
            get {
                return this.VideoField;
            }
            set {
                if ((this.VideoField.Equals(value) != true)) {
                    this.VideoField = value;
                    this.RaisePropertyChanged("Video");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((object.ReferenceEquals(this.DatumField, value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBlack.ServiceBlackSoap")]
    public interface ServiceBlackSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inloggning", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.InloggningResponse> InloggningAsync(BlackTVWin10.ServiceBlack.InloggningRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SkickaEpost", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.SkickaEpostResponse> SkickaEpostAsync(BlackTVWin10.ServiceBlack.SkickaEpostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.HelloUserResponse> HelloUserAsync(BlackTVWin10.ServiceBlack.HelloUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTV", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getTVResponse> getTVAsync(BlackTVWin10.ServiceBlack.getTVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGrupper", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getGrupperResponse> getGrupperAsync(BlackTVWin10.ServiceBlack.getGrupperRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/nyBlackTV", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.nyBlackTVResponse> nyBlackTVAsync(BlackTVWin10.ServiceBlack.nyBlackTVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBlackTV", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.UpdateBlackTVResponse> UpdateBlackTVAsync(BlackTVWin10.ServiceBlack.UpdateBlackTVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RaderaBlackTV", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.RaderaBlackTVResponse> RaderaBlackTVAsync(BlackTVWin10.ServiceBlack.RaderaBlackTVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RaderaGrupp", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.RaderaGruppResponse> RaderaGruppAsync(BlackTVWin10.ServiceBlack.RaderaGruppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NyGrupp", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.NyGruppResponse> NyGruppAsync(BlackTVWin10.ServiceBlack.NyGruppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditGrupp", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.EditGruppResponse> EditGruppAsync(BlackTVWin10.ServiceBlack.EditGruppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTVjson", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getTVjsonResponse> getTVjsonAsync(BlackTVWin10.ServiceBlack.getTVjsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uppdateraKontakt", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.uppdateraKontaktResponse> uppdateraKontaktAsync(BlackTVWin10.ServiceBlack.uppdateraKontaktRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getKontakt", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getKontaktResponse> getKontaktAsync(BlackTVWin10.ServiceBlack.getKontaktRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getShowBlackTv", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getShowBlackTvResponse> getShowBlackTvAsync(BlackTVWin10.ServiceBlack.getShowBlackTvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loggaIn", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.loggaInResponse> loggaInAsync(BlackTVWin10.ServiceBlack.loggaInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGrupper10", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getGrupper10Response> getGrupper10Async(BlackTVWin10.ServiceBlack.getGrupper10Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getShowBlackTvWEB", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getShowBlackTvWEBResponse> getShowBlackTvWEBAsync(BlackTVWin10.ServiceBlack.getShowBlackTvWEBRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InloggningRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Inloggning", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.InloggningRequestBody Body;
        
        public InloggningRequest() {
        }
        
        public InloggningRequest(BlackTVWin10.ServiceBlack.InloggningRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InloggningRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string foretag;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string losen;
        
        public InloggningRequestBody() {
        }
        
        public InloggningRequestBody(string foretag, string losen) {
            this.foretag = foretag;
            this.losen = losen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InloggningResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InloggningResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.InloggningResponseBody Body;
        
        public InloggningResponse() {
        }
        
        public InloggningResponse(BlackTVWin10.ServiceBlack.InloggningResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InloggningResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InloggningResult;
        
        public InloggningResponseBody() {
        }
        
        public InloggningResponseBody(string InloggningResult) {
            this.InloggningResult = InloggningResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SkickaEpostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SkickaEpost", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.SkickaEpostRequestBody Body;
        
        public SkickaEpostRequest() {
        }
        
        public SkickaEpostRequest(BlackTVWin10.ServiceBlack.SkickaEpostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SkickaEpostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string text;
        
        public SkickaEpostRequestBody() {
        }
        
        public SkickaEpostRequestBody(string to, string from, string subject, string text) {
            this.to = to;
            this.from = from;
            this.subject = subject;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SkickaEpostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SkickaEpostResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.SkickaEpostResponseBody Body;
        
        public SkickaEpostResponse() {
        }
        
        public SkickaEpostResponse(BlackTVWin10.ServiceBlack.SkickaEpostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SkickaEpostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SkickaEpostResult;
        
        public SkickaEpostResponseBody() {
        }
        
        public SkickaEpostResponseBody(string SkickaEpostResult) {
            this.SkickaEpostResult = SkickaEpostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloUser", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.HelloUserRequestBody Body;
        
        public HelloUserRequest() {
        }
        
        public HelloUserRequest(BlackTVWin10.ServiceBlack.HelloUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string foretag;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string losen;
        
        public HelloUserRequestBody() {
        }
        
        public HelloUserRequestBody(string foretag, string losen) {
            this.foretag = foretag;
            this.losen = losen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.HelloUserResponseBody Body;
        
        public HelloUserResponse() {
        }
        
        public HelloUserResponse(BlackTVWin10.ServiceBlack.HelloUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloUserResult;
        
        public HelloUserResponseBody() {
        }
        
        public HelloUserResponseBody(string HelloUserResult) {
            this.HelloUserResult = HelloUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTV", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getTVRequestBody Body;
        
        public getTVRequest() {
        }
        
        public getTVRequest(BlackTVWin10.ServiceBlack.getTVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int foretagsid;
        
        public getTVRequestBody() {
        }
        
        public getTVRequestBody(int foretagsid) {
            this.foretagsid = foretagsid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTVResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getTVResponseBody Body;
        
        public getTVResponse() {
        }
        
        public getTVResponse(BlackTVWin10.ServiceBlack.getTVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<BlackTVWin10.ServiceBlack.TVrader> getTVResult;
        
        public getTVResponseBody() {
        }
        
        public getTVResponseBody(System.Collections.ObjectModel.ObservableCollection<BlackTVWin10.ServiceBlack.TVrader> getTVResult) {
            this.getTVResult = getTVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGrupperRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGrupper", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getGrupperRequestBody Body;
        
        public getGrupperRequest() {
        }
        
        public getGrupperRequest(BlackTVWin10.ServiceBlack.getGrupperRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGrupperRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string foretagsid;
        
        public getGrupperRequestBody() {
        }
        
        public getGrupperRequestBody(string foretagsid) {
            this.foretagsid = foretagsid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGrupperResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGrupperResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getGrupperResponseBody Body;
        
        public getGrupperResponse() {
        }
        
        public getGrupperResponse(BlackTVWin10.ServiceBlack.getGrupperResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGrupperResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object getGrupperResult;
        
        public getGrupperResponseBody() {
        }
        
        public getGrupperResponseBody(object getGrupperResult) {
            this.getGrupperResult = getGrupperResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nyBlackTVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nyBlackTV", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.nyBlackTVRequestBody Body;
        
        public nyBlackTVRequest() {
        }
        
        public nyBlackTVRequest(BlackTVWin10.ServiceBlack.nyBlackTVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class nyBlackTVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ForetagsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string info;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int grupp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tag;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int video;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Datum;
        
        public nyBlackTVRequestBody() {
        }
        
        public nyBlackTVRequestBody(int ForetagsID, string info, int grupp, string tag, int video, string Datum) {
            this.ForetagsID = ForetagsID;
            this.info = info;
            this.grupp = grupp;
            this.tag = tag;
            this.video = video;
            this.Datum = Datum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nyBlackTVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nyBlackTVResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.nyBlackTVResponseBody Body;
        
        public nyBlackTVResponse() {
        }
        
        public nyBlackTVResponse(BlackTVWin10.ServiceBlack.nyBlackTVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class nyBlackTVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nyBlackTVResult;
        
        public nyBlackTVResponseBody() {
        }
        
        public nyBlackTVResponseBody(string nyBlackTVResult) {
            this.nyBlackTVResult = nyBlackTVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBlackTVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBlackTV", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.UpdateBlackTVRequestBody Body;
        
        public UpdateBlackTVRequest() {
        }
        
        public UpdateBlackTVRequest(BlackTVWin10.ServiceBlack.UpdateBlackTVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBlackTVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ForetagsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string info;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int grupp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tag;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int video;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Datum;
        
        public UpdateBlackTVRequestBody() {
        }
        
        public UpdateBlackTVRequestBody(int id, int ForetagsID, string info, int grupp, string tag, int video, string Datum) {
            this.id = id;
            this.ForetagsID = ForetagsID;
            this.info = info;
            this.grupp = grupp;
            this.tag = tag;
            this.video = video;
            this.Datum = Datum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBlackTVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBlackTVResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.UpdateBlackTVResponseBody Body;
        
        public UpdateBlackTVResponse() {
        }
        
        public UpdateBlackTVResponse(BlackTVWin10.ServiceBlack.UpdateBlackTVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBlackTVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateBlackTVResult;
        
        public UpdateBlackTVResponseBody() {
        }
        
        public UpdateBlackTVResponseBody(string UpdateBlackTVResult) {
            this.UpdateBlackTVResult = UpdateBlackTVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RaderaBlackTVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RaderaBlackTV", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.RaderaBlackTVRequestBody Body;
        
        public RaderaBlackTVRequest() {
        }
        
        public RaderaBlackTVRequest(BlackTVWin10.ServiceBlack.RaderaBlackTVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RaderaBlackTVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public RaderaBlackTVRequestBody() {
        }
        
        public RaderaBlackTVRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RaderaBlackTVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RaderaBlackTVResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.RaderaBlackTVResponseBody Body;
        
        public RaderaBlackTVResponse() {
        }
        
        public RaderaBlackTVResponse(BlackTVWin10.ServiceBlack.RaderaBlackTVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RaderaBlackTVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RaderaBlackTVResult;
        
        public RaderaBlackTVResponseBody() {
        }
        
        public RaderaBlackTVResponseBody(string RaderaBlackTVResult) {
            this.RaderaBlackTVResult = RaderaBlackTVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RaderaGruppRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RaderaGrupp", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.RaderaGruppRequestBody Body;
        
        public RaderaGruppRequest() {
        }
        
        public RaderaGruppRequest(BlackTVWin10.ServiceBlack.RaderaGruppRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RaderaGruppRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public RaderaGruppRequestBody() {
        }
        
        public RaderaGruppRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RaderaGruppResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RaderaGruppResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.RaderaGruppResponseBody Body;
        
        public RaderaGruppResponse() {
        }
        
        public RaderaGruppResponse(BlackTVWin10.ServiceBlack.RaderaGruppResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RaderaGruppResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RaderaGruppResult;
        
        public RaderaGruppResponseBody() {
        }
        
        public RaderaGruppResponseBody(string RaderaGruppResult) {
            this.RaderaGruppResult = RaderaGruppResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NyGruppRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NyGrupp", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.NyGruppRequestBody Body;
        
        public NyGruppRequest() {
        }
        
        public NyGruppRequest(BlackTVWin10.ServiceBlack.NyGruppRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NyGruppRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ForetagsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string info;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Grupp;
        
        public NyGruppRequestBody() {
        }
        
        public NyGruppRequestBody(int ForetagsID, string info, string Grupp) {
            this.ForetagsID = ForetagsID;
            this.info = info;
            this.Grupp = Grupp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NyGruppResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NyGruppResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.NyGruppResponseBody Body;
        
        public NyGruppResponse() {
        }
        
        public NyGruppResponse(BlackTVWin10.ServiceBlack.NyGruppResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NyGruppResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NyGruppResult;
        
        public NyGruppResponseBody() {
        }
        
        public NyGruppResponseBody(string NyGruppResult) {
            this.NyGruppResult = NyGruppResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditGruppRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditGrupp", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.EditGruppRequestBody Body;
        
        public EditGruppRequest() {
        }
        
        public EditGruppRequest(BlackTVWin10.ServiceBlack.EditGruppRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditGruppRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ForetagsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string info;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Grupp;
        
        public EditGruppRequestBody() {
        }
        
        public EditGruppRequestBody(int id, int ForetagsID, string info, string Grupp) {
            this.id = id;
            this.ForetagsID = ForetagsID;
            this.info = info;
            this.Grupp = Grupp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditGruppResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditGruppResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.EditGruppResponseBody Body;
        
        public EditGruppResponse() {
        }
        
        public EditGruppResponse(BlackTVWin10.ServiceBlack.EditGruppResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditGruppResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EditGruppResult;
        
        public EditGruppResponseBody() {
        }
        
        public EditGruppResponseBody(string EditGruppResult) {
            this.EditGruppResult = EditGruppResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTVjsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTVjson", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getTVjsonRequestBody Body;
        
        public getTVjsonRequest() {
        }
        
        public getTVjsonRequest(BlackTVWin10.ServiceBlack.getTVjsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTVjsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ftgid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int grupp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime Datum;
        
        public getTVjsonRequestBody() {
        }
        
        public getTVjsonRequestBody(int ftgid, int grupp, System.DateTime Datum) {
            this.ftgid = ftgid;
            this.grupp = grupp;
            this.Datum = Datum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTVjsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTVjsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getTVjsonResponseBody Body;
        
        public getTVjsonResponse() {
        }
        
        public getTVjsonResponse(BlackTVWin10.ServiceBlack.getTVjsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTVjsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTVjsonResult;
        
        public getTVjsonResponseBody() {
        }
        
        public getTVjsonResponseBody(string getTVjsonResult) {
            this.getTVjsonResult = getTVjsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uppdateraKontaktRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uppdateraKontakt", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.uppdateraKontaktRequestBody Body;
        
        public uppdateraKontaktRequest() {
        }
        
        public uppdateraKontaktRequest(BlackTVWin10.ServiceBlack.uppdateraKontaktRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class uppdateraKontaktRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Foretag;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string losenord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Adress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string postnr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ort;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string epost;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string kontaktperson;
        
        public uppdateraKontaktRequestBody() {
        }
        
        public uppdateraKontaktRequestBody(int id, string Foretag, string losenord, string Adress, string postnr, string ort, string tel, string epost, string kontaktperson) {
            this.id = id;
            this.Foretag = Foretag;
            this.losenord = losenord;
            this.Adress = Adress;
            this.postnr = postnr;
            this.ort = ort;
            this.tel = tel;
            this.epost = epost;
            this.kontaktperson = kontaktperson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uppdateraKontaktResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uppdateraKontaktResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.uppdateraKontaktResponseBody Body;
        
        public uppdateraKontaktResponse() {
        }
        
        public uppdateraKontaktResponse(BlackTVWin10.ServiceBlack.uppdateraKontaktResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class uppdateraKontaktResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uppdateraKontaktResult;
        
        public uppdateraKontaktResponseBody() {
        }
        
        public uppdateraKontaktResponseBody(string uppdateraKontaktResult) {
            this.uppdateraKontaktResult = uppdateraKontaktResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKontaktRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getKontakt", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getKontaktRequestBody Body;
        
        public getKontaktRequest() {
        }
        
        public getKontaktRequest(BlackTVWin10.ServiceBlack.getKontaktRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getKontaktRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getKontaktRequestBody() {
        }
        
        public getKontaktRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKontaktResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getKontaktResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getKontaktResponseBody Body;
        
        public getKontaktResponse() {
        }
        
        public getKontaktResponse(BlackTVWin10.ServiceBlack.getKontaktResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getKontaktResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object getKontaktResult;
        
        public getKontaktResponseBody() {
        }
        
        public getKontaktResponseBody(object getKontaktResult) {
            this.getKontaktResult = getKontaktResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getShowBlackTvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getShowBlackTv", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getShowBlackTvRequestBody Body;
        
        public getShowBlackTvRequest() {
        }
        
        public getShowBlackTvRequest(BlackTVWin10.ServiceBlack.getShowBlackTvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getShowBlackTvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ftgid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int grupp;
        
        public getShowBlackTvRequestBody() {
        }
        
        public getShowBlackTvRequestBody(int ftgid, int grupp) {
            this.ftgid = ftgid;
            this.grupp = grupp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getShowBlackTvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getShowBlackTvResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getShowBlackTvResponseBody Body;
        
        public getShowBlackTvResponse() {
        }
        
        public getShowBlackTvResponse(BlackTVWin10.ServiceBlack.getShowBlackTvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getShowBlackTvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object getShowBlackTvResult;
        
        public getShowBlackTvResponseBody() {
        }
        
        public getShowBlackTvResponseBody(object getShowBlackTvResult) {
            this.getShowBlackTvResult = getShowBlackTvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loggaInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loggaIn", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.loggaInRequestBody Body;
        
        public loggaInRequest() {
        }
        
        public loggaInRequest(BlackTVWin10.ServiceBlack.loggaInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loggaInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loggaInRequestBody() {
        }
        
        public loggaInRequestBody(string user, string password) {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loggaInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loggaInResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.loggaInResponseBody Body;
        
        public loggaInResponse() {
        }
        
        public loggaInResponse(BlackTVWin10.ServiceBlack.loggaInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loggaInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loggaInResult;
        
        public loggaInResponseBody() {
        }
        
        public loggaInResponseBody(string loggaInResult) {
            this.loggaInResult = loggaInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGrupper10Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGrupper10", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getGrupper10RequestBody Body;
        
        public getGrupper10Request() {
        }
        
        public getGrupper10Request(BlackTVWin10.ServiceBlack.getGrupper10RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGrupper10RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int foretagsid;
        
        public getGrupper10RequestBody() {
        }
        
        public getGrupper10RequestBody(int foretagsid) {
            this.foretagsid = foretagsid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGrupper10Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGrupper10Response", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getGrupper10ResponseBody Body;
        
        public getGrupper10Response() {
        }
        
        public getGrupper10Response(BlackTVWin10.ServiceBlack.getGrupper10ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGrupper10ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getGrupper10Result;
        
        public getGrupper10ResponseBody() {
        }
        
        public getGrupper10ResponseBody(string getGrupper10Result) {
            this.getGrupper10Result = getGrupper10Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getShowBlackTvWEBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getShowBlackTvWEB", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getShowBlackTvWEBRequestBody Body;
        
        public getShowBlackTvWEBRequest() {
        }
        
        public getShowBlackTvWEBRequest(BlackTVWin10.ServiceBlack.getShowBlackTvWEBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getShowBlackTvWEBRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ftgid;
        
        public getShowBlackTvWEBRequestBody() {
        }
        
        public getShowBlackTvWEBRequestBody(string ftgid) {
            this.ftgid = ftgid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getShowBlackTvWEBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getShowBlackTvWEBResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlackTVWin10.ServiceBlack.getShowBlackTvWEBResponseBody Body;
        
        public getShowBlackTvWEBResponse() {
        }
        
        public getShowBlackTvWEBResponse(BlackTVWin10.ServiceBlack.getShowBlackTvWEBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getShowBlackTvWEBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object getShowBlackTvWEBResult;
        
        public getShowBlackTvWEBResponseBody() {
        }
        
        public getShowBlackTvWEBResponseBody(object getShowBlackTvWEBResult) {
            this.getShowBlackTvWEBResult = getShowBlackTvWEBResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceBlackSoapChannel : BlackTVWin10.ServiceBlack.ServiceBlackSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBlackSoapClient : System.ServiceModel.ClientBase<BlackTVWin10.ServiceBlack.ServiceBlackSoap>, BlackTVWin10.ServiceBlack.ServiceBlackSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceBlackSoapClient() : 
                base(ServiceBlackSoapClient.GetDefaultBinding(), ServiceBlackSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.ServiceBlackSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBlackSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceBlackSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceBlackSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBlackSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceBlackSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBlackSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceBlackSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBlackSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.InloggningResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.InloggningAsync(BlackTVWin10.ServiceBlack.InloggningRequest request) {
            return base.Channel.InloggningAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.InloggningResponse> InloggningAsync(string foretag, string losen) {
            BlackTVWin10.ServiceBlack.InloggningRequest inValue = new BlackTVWin10.ServiceBlack.InloggningRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.InloggningRequestBody();
            inValue.Body.foretag = foretag;
            inValue.Body.losen = losen;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).InloggningAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.SkickaEpostResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.SkickaEpostAsync(BlackTVWin10.ServiceBlack.SkickaEpostRequest request) {
            return base.Channel.SkickaEpostAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.SkickaEpostResponse> SkickaEpostAsync(string to, string from, string subject, string text) {
            BlackTVWin10.ServiceBlack.SkickaEpostRequest inValue = new BlackTVWin10.ServiceBlack.SkickaEpostRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.SkickaEpostRequestBody();
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.subject = subject;
            inValue.Body.text = text;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).SkickaEpostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.HelloUserResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.HelloUserAsync(BlackTVWin10.ServiceBlack.HelloUserRequest request) {
            return base.Channel.HelloUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.HelloUserResponse> HelloUserAsync(string foretag, string losen) {
            BlackTVWin10.ServiceBlack.HelloUserRequest inValue = new BlackTVWin10.ServiceBlack.HelloUserRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.HelloUserRequestBody();
            inValue.Body.foretag = foretag;
            inValue.Body.losen = losen;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).HelloUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getTVResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.getTVAsync(BlackTVWin10.ServiceBlack.getTVRequest request) {
            return base.Channel.getTVAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getTVResponse> getTVAsync(int foretagsid) {
            BlackTVWin10.ServiceBlack.getTVRequest inValue = new BlackTVWin10.ServiceBlack.getTVRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.getTVRequestBody();
            inValue.Body.foretagsid = foretagsid;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).getTVAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getGrupperResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.getGrupperAsync(BlackTVWin10.ServiceBlack.getGrupperRequest request) {
            return base.Channel.getGrupperAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getGrupperResponse> getGrupperAsync(string foretagsid) {
            BlackTVWin10.ServiceBlack.getGrupperRequest inValue = new BlackTVWin10.ServiceBlack.getGrupperRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.getGrupperRequestBody();
            inValue.Body.foretagsid = foretagsid;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).getGrupperAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.nyBlackTVResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.nyBlackTVAsync(BlackTVWin10.ServiceBlack.nyBlackTVRequest request) {
            return base.Channel.nyBlackTVAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.nyBlackTVResponse> nyBlackTVAsync(int ForetagsID, string info, int grupp, string tag, int video, string Datum) {
            BlackTVWin10.ServiceBlack.nyBlackTVRequest inValue = new BlackTVWin10.ServiceBlack.nyBlackTVRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.nyBlackTVRequestBody();
            inValue.Body.ForetagsID = ForetagsID;
            inValue.Body.info = info;
            inValue.Body.grupp = grupp;
            inValue.Body.tag = tag;
            inValue.Body.video = video;
            inValue.Body.Datum = Datum;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).nyBlackTVAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.UpdateBlackTVResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.UpdateBlackTVAsync(BlackTVWin10.ServiceBlack.UpdateBlackTVRequest request) {
            return base.Channel.UpdateBlackTVAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.UpdateBlackTVResponse> UpdateBlackTVAsync(int id, int ForetagsID, string info, int grupp, string tag, int video, string Datum) {
            BlackTVWin10.ServiceBlack.UpdateBlackTVRequest inValue = new BlackTVWin10.ServiceBlack.UpdateBlackTVRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.UpdateBlackTVRequestBody();
            inValue.Body.id = id;
            inValue.Body.ForetagsID = ForetagsID;
            inValue.Body.info = info;
            inValue.Body.grupp = grupp;
            inValue.Body.tag = tag;
            inValue.Body.video = video;
            inValue.Body.Datum = Datum;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).UpdateBlackTVAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.RaderaBlackTVResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.RaderaBlackTVAsync(BlackTVWin10.ServiceBlack.RaderaBlackTVRequest request) {
            return base.Channel.RaderaBlackTVAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.RaderaBlackTVResponse> RaderaBlackTVAsync(int id) {
            BlackTVWin10.ServiceBlack.RaderaBlackTVRequest inValue = new BlackTVWin10.ServiceBlack.RaderaBlackTVRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.RaderaBlackTVRequestBody();
            inValue.Body.id = id;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).RaderaBlackTVAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.RaderaGruppResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.RaderaGruppAsync(BlackTVWin10.ServiceBlack.RaderaGruppRequest request) {
            return base.Channel.RaderaGruppAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.RaderaGruppResponse> RaderaGruppAsync(int id) {
            BlackTVWin10.ServiceBlack.RaderaGruppRequest inValue = new BlackTVWin10.ServiceBlack.RaderaGruppRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.RaderaGruppRequestBody();
            inValue.Body.id = id;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).RaderaGruppAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.NyGruppResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.NyGruppAsync(BlackTVWin10.ServiceBlack.NyGruppRequest request) {
            return base.Channel.NyGruppAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.NyGruppResponse> NyGruppAsync(int ForetagsID, string info, string Grupp) {
            BlackTVWin10.ServiceBlack.NyGruppRequest inValue = new BlackTVWin10.ServiceBlack.NyGruppRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.NyGruppRequestBody();
            inValue.Body.ForetagsID = ForetagsID;
            inValue.Body.info = info;
            inValue.Body.Grupp = Grupp;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).NyGruppAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.EditGruppResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.EditGruppAsync(BlackTVWin10.ServiceBlack.EditGruppRequest request) {
            return base.Channel.EditGruppAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.EditGruppResponse> EditGruppAsync(int id, int ForetagsID, string info, string Grupp) {
            BlackTVWin10.ServiceBlack.EditGruppRequest inValue = new BlackTVWin10.ServiceBlack.EditGruppRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.EditGruppRequestBody();
            inValue.Body.id = id;
            inValue.Body.ForetagsID = ForetagsID;
            inValue.Body.info = info;
            inValue.Body.Grupp = Grupp;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).EditGruppAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getTVjsonResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.getTVjsonAsync(BlackTVWin10.ServiceBlack.getTVjsonRequest request) {
            return base.Channel.getTVjsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getTVjsonResponse> getTVjsonAsync(int ftgid, int grupp, System.DateTime Datum) {
            BlackTVWin10.ServiceBlack.getTVjsonRequest inValue = new BlackTVWin10.ServiceBlack.getTVjsonRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.getTVjsonRequestBody();
            inValue.Body.ftgid = ftgid;
            inValue.Body.grupp = grupp;
            inValue.Body.Datum = Datum;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).getTVjsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.uppdateraKontaktResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.uppdateraKontaktAsync(BlackTVWin10.ServiceBlack.uppdateraKontaktRequest request) {
            return base.Channel.uppdateraKontaktAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.uppdateraKontaktResponse> uppdateraKontaktAsync(int id, string Foretag, string losenord, string Adress, string postnr, string ort, string tel, string epost, string kontaktperson) {
            BlackTVWin10.ServiceBlack.uppdateraKontaktRequest inValue = new BlackTVWin10.ServiceBlack.uppdateraKontaktRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.uppdateraKontaktRequestBody();
            inValue.Body.id = id;
            inValue.Body.Foretag = Foretag;
            inValue.Body.losenord = losenord;
            inValue.Body.Adress = Adress;
            inValue.Body.postnr = postnr;
            inValue.Body.ort = ort;
            inValue.Body.tel = tel;
            inValue.Body.epost = epost;
            inValue.Body.kontaktperson = kontaktperson;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).uppdateraKontaktAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getKontaktResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.getKontaktAsync(BlackTVWin10.ServiceBlack.getKontaktRequest request) {
            return base.Channel.getKontaktAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getKontaktResponse> getKontaktAsync(int id) {
            BlackTVWin10.ServiceBlack.getKontaktRequest inValue = new BlackTVWin10.ServiceBlack.getKontaktRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.getKontaktRequestBody();
            inValue.Body.id = id;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).getKontaktAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getShowBlackTvResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.getShowBlackTvAsync(BlackTVWin10.ServiceBlack.getShowBlackTvRequest request) {
            return base.Channel.getShowBlackTvAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getShowBlackTvResponse> getShowBlackTvAsync(int ftgid, int grupp) {
            BlackTVWin10.ServiceBlack.getShowBlackTvRequest inValue = new BlackTVWin10.ServiceBlack.getShowBlackTvRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.getShowBlackTvRequestBody();
            inValue.Body.ftgid = ftgid;
            inValue.Body.grupp = grupp;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).getShowBlackTvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.loggaInResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.loggaInAsync(BlackTVWin10.ServiceBlack.loggaInRequest request) {
            return base.Channel.loggaInAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.loggaInResponse> loggaInAsync(string user, string password) {
            BlackTVWin10.ServiceBlack.loggaInRequest inValue = new BlackTVWin10.ServiceBlack.loggaInRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.loggaInRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).loggaInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getGrupper10Response> BlackTVWin10.ServiceBlack.ServiceBlackSoap.getGrupper10Async(BlackTVWin10.ServiceBlack.getGrupper10Request request) {
            return base.Channel.getGrupper10Async(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getGrupper10Response> getGrupper10Async(int foretagsid) {
            BlackTVWin10.ServiceBlack.getGrupper10Request inValue = new BlackTVWin10.ServiceBlack.getGrupper10Request();
            inValue.Body = new BlackTVWin10.ServiceBlack.getGrupper10RequestBody();
            inValue.Body.foretagsid = foretagsid;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).getGrupper10Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getShowBlackTvWEBResponse> BlackTVWin10.ServiceBlack.ServiceBlackSoap.getShowBlackTvWEBAsync(BlackTVWin10.ServiceBlack.getShowBlackTvWEBRequest request) {
            return base.Channel.getShowBlackTvWEBAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackTVWin10.ServiceBlack.getShowBlackTvWEBResponse> getShowBlackTvWEBAsync(string ftgid) {
            BlackTVWin10.ServiceBlack.getShowBlackTvWEBRequest inValue = new BlackTVWin10.ServiceBlack.getShowBlackTvWEBRequest();
            inValue.Body = new BlackTVWin10.ServiceBlack.getShowBlackTvWEBRequestBody();
            inValue.Body.ftgid = ftgid;
            return ((BlackTVWin10.ServiceBlack.ServiceBlackSoap)(this)).getShowBlackTvWEBAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ServiceBlackSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ServiceBlackSoap)) {
                return new System.ServiceModel.EndpointAddress("http://blacktv.se/ServiceBlack.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ServiceBlackSoapClient.GetBindingForEndpoint(EndpointConfiguration.ServiceBlackSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ServiceBlackSoapClient.GetEndpointAddress(EndpointConfiguration.ServiceBlackSoap);
        }
        
        public enum EndpointConfiguration {
            
            ServiceBlackSoap,
        }
    }
}
